drinks = {
    "espresso":{
        "ingredients":{
            "water":50,
            "coffee":18,
            "milk":0
        },
        "price":90,
    },
    "latte":{
        "ingredients":{
            "water":200,
            "coffee":24,
            "milk":150,
        },
        "price":180,
    },
    "cappuccino":{
        "ingredients":{
            "water":250,
            "coffee":24,
            "milk":100,
        },
        "price":280,
    },
}